### ISSUE TITLE
How do I start this?

### ISSUE THREAD

**Issue by Industrial** [hij1nx/levelui#50]
I did a `npm i -g levelui` but there is no levelui in my path. Other tools installed with -g are in my path.

**Comment by heapwolf** [comment]
i suspect that it's probably just so out of date that it's not working. a lot of people have expressed interest so im just waiting for a window of opportunity to work on it. I should get a free weekend soon.

**Comment by Industrial** [comment]
Thanks, it's the only tool I see (from the screenshot) that is able  to connect to a multilevel server over TCP? This is my main use case :-)

I'm not sure I can open the DB file for use with two processes at the same time, and my multilevel server always is the one serving it.

I'm trying to serve Levelgraph over Multilevel so that I can use it to power GraphQL API's

**Comment by heapwolf** [comment]
ah. ok. there are really two options...

1. you could use [level-party](https://github.com/substack/level-party), which makes it so that multiple processes can connect to the same instance of leveldb.

2. create a simple tcp or http server that exposes the methods you care about and then have your other processes connect to your instance.

**Comment by Sjors** [comment]
I just cloned the repository, installed via `npm install` and ran with `nom start`. Unfortunately that resulted in a somewhat broken UI:

<img width="906" alt="ui" src="https://user-images.githubusercontent.com/10217/38314020-a61e710a-3825-11e8-89a5-e53f6c7f21f1.png">

I also followed the instruction in the README, slightly modified:

```
cd node_modules/leveldown
npm install -g node-gyp
env HOME=~/.electron-gyp && node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```

Unfortunately that throws an error:

```
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:1:
In file included from /Users/xxxxxx/.node-gyp/0.28.1/src/node.h:42:
/Users/xxxxxx/.node-gyp/0.28.1/deps/v8/include/v8.h:6859:54: error: 'CreateHandle' is a protected member of 'v8::HandleScope'
  return Handle<T>(reinterpret_cast<T*>(HandleScope::CreateHandle(
                                        ~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/xxxxxx/.node-gyp/0.28.1/deps/v8/include/v8.h:959:29: note: declared protected here
  static internal::Object** CreateHandle(internal::Isolate* isolate,
                            ^
1 error generated.
```

Using macOS 10.13.4 with node v8.9.4.

**Comment by fgomescg** [comment]
Same here... on linux

**Comment by Industrial** [comment]
I'd leave LevelDB for another solution. Like RocksDB or something. Not closing the ticket, however.

**Comment by Industrial** [comment]
It's dead.
